exclude_patterns:
- "config/"
- "db/"
- "database/"
- "**/migrations/"
- "**/seeds/"
- "**/factories/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "packages/"
- "**/robsontenorio/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
