apiVersion: v1
kind: Service
metadata:
  name:  logistik-api-app
  namespace: pikobar-logistik
  labels:
    app:  logistik-api-app
spec:
  selector:
    app:  logistik-api-app
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
